### ISSUE TITLE
Install OK, but tests fails (Mojo 0.999950)

### ISSUE THREAD

**Issue by fleveillee** [forwardever/mojox-scaffold#1]
I am new at this, let me know if you need more info.

Mac OSX Snow Leopard 10.6.5
macports installed perl 5.12
This is perl 5, version 12, subversion 2 (v5.12.2) built for darwin-thread-multi-2level
###### Full log won't show, but is saved - edit this so see full log.

$ sudo cpanm -v .

You have make /usr/bin/make
You have LWP 5.837
You have /usr/bin/tar: bsdtar 2.6.2 - libarchive 2.6.2
You have /usr/bin/unzip
--> Working on .
Entering /Users/fleveillee/Downloads/forwardever-mojox-scaffold-b0c1cd2
Configuring /Users/fleveillee/Downloads/forwardever-mojox-scaffold-b0c1cd2 ... Running Build.PL
WARNING: the following files are missing in your kit:
    MYMETA.yml
Please inform the author.

Creating new 'MYMETA.yml' with configuration results
Creating new 'Build' script for 'Mojolicious-Plugin-ResourcefulRoutes' version '0.04'
OK
Checking dependencies from MYMETA.yml ...
Finding PREREQ from Makefile ...
Checking if you have Mojolicious 0.999929 ... Yes (0.999950)
Checking if you have Test::More 0 ... Yes (0.96)
Checking if you have Mojolicious 0.999931 ... Yes (0.999950)
Building and testing Mojolicious-Plugin-ResourcefulRoutes-0.04 ... Building Mojolicious-Plugin-ResourcefulRoutes
t/resources.t .. 1/125 
   Failed test '200 OK'
   at t/resources.t line 47.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 47.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>

expected: 'Template for displaying a form that allows to delete an existing resource item! Route name: users_delete_form'
Use of uninitialized value in lc at /Users/fleveillee/Downloads/forwardever-mojox-scaffold-b0c1cd2/blib/lib/Mojolicious/Plugin/ResourcefulRoutes.pm line 20.
Use of uninitialized value in lc at /Users/fleveillee/Downloads/forwardever-mojox-scaffold-b0c1cd2/blib/lib/Mojolicious/Plugin/ResourcefulRoutes.pm line 23.
t/resources.t .. 59/125 

   Failed test '200 OK'
   at t/resources.t line 115.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 115.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>

expected: 'Template for displaying a form that allows to delete an existing resource item! Route name: admin-users_delete_form'
Use of uninitialized value in lc at /Users/fleveillee/Downloads/forwardever-mojox-scaffold-b0c1cd2/blib/lib/Mojolicious/Plugin/ResourcefulRoutes.pm line 20.
Use of uninitialized value in lc at /Users/fleveillee/Downloads/forwardever-mojox-scaffold-b0c1cd2/blib/lib/Mojolicious/Plugin/ResourcefulRoutes.pm line 23.

   Failed test '200 OK'
   at t/resources.t line 161.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 161.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>
 '
     expected: 'Template for displaying a form that allows to create a new resource item! Route name: member_new_form'

   Failed test '200 OK'
   at t/resources.t line 167.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 167.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>
 '
     expected: 'Template for displaying a single resource item! Route name: member_show'

   Failed test '200 OK'
   at t/resources.t line 173.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 173.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>
 '
     expected: 'Template for displaying a form that allows to edit an existing resource item! Route name: member_edit_form'

   Failed test '200 OK'
   at t/resources.t line 179.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 179.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>
 '
     expected: 'Template for displaying a form that allows to delete an existing resource item! Route name: member_delete_form'
Use of uninitialized value in lc at /Users/fleveillee/Downloads/forwardever-mojox-scaffold-b0c1cd2/blib/lib/Mojolicious/Plugin/ResourcefulRoutes.pm line 20.
Use of uninitialized value in lc at /Users/fleveillee/Downloads/forwardever-mojox-scaffold-b0c1cd2/blib/lib/Mojolicious/Plugin/ResourcefulRoutes.pm line 23.

   Failed test '200 OK'
   at t/resources.t line 185.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 185.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>
 '
     expected: 'POST request, create method executed! Route name: member_create'

   Failed test '200 OK'
   at t/resources.t line 191.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 191.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>
 '
     expected: 'PUT request, update method executed! Route name: member_update'

   Failed test '200 OK'
   at t/resources.t line 197.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 197.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>
 '
     expected: 'PUT request, update method executed! Route name: member_update'

   Failed test '200 OK'
   at t/resources.t line 203.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 203.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>
 '
     expected: 'DELETE request, delete method executed! Route name: member_delete'

   Failed test '200 OK'
   at t/resources.t line 209.
          got: '404'
     expected: '200'

   Failed test 'exact match for content'
   at t/resources.t line 209.
          got: '<!doctype html><html>
     <head>
         <title>Not Found</title>
         <style type="text/css">
             body {
                 font: 0.9em Verdana, "Bitstream Vera Sans", sans-serif;
             }
         </style>
     </head>
     <body>
         <div>
             Page not found, want to go <a href="http://localhost:19687">home</a>?
         </div>
     </body>
 </html>
 '
     expected: 'DELETE request, delete method executed! Route name: member_delete'
 Looks like you failed 22 tests of 125.
t/resources.t .. Dubious, test returned 22 (wstat 5632, 0x1600)
Failed 22/125 subtests 
## Test Summary Report

t/resources.t (Wstat: 5632 Tests: 125 Failed: 22)
  Failed tests:  20, 22, 63, 65, 91, 93, 95, 97, 99, 101
                103, 105, 107, 109, 111, 113, 115, 117
                119, 121, 123, 125
  Non-zero exit status: 22
Files=1, Tests=125,  1 wallclock secs ( 0.06 usr  0.02 sys +  0.81 cusr  0.08 csys =  0.97 CPU)
Result: FAIL
Failed 1/1 test programs. 22/125 subtests failed.
FAIL
! Installing . failed. See /Users/fleveillee/.cpanm/build.log for details.

**Comment by forwardever** [comment]
hello, thanks for your feedback

I actually forgot to add some test files, so tests passed on my computer, but failed when installing from Github

would be great if you could tell me if everything works fine now, thanks!

**Comment by fleveillee** [comment]
Thanks a lot!

All tests successful.
Files=1, Tests=125,  1 wallclock secs ( 0.05 usr  0.02 sys +  0.76 cusr  0.09 csys =  0.92 CPU)
Result: PASS
Building Mojolicious-Plugin-ResourcefulRoutes
Installing /opt/local/lib/perl5/site_perl/5.12.2/Mojolicious/Plugin/ResourcefulRoutes.pm
OK
Successfully installed Mojolicious-Plugin-ResourcefulRoutes-0.04
